#!/bin/bash

LIBFREENECT2_PATH="/Users/groux/git/libfreenect2/build/lib"
export DYLD_LIBRARY_PATH="$LIBFREENECT2_PATH:$DYLD_LIBRARY_PATH"

# Utility to quickly start task, like `./run nuru.recorder`

cd "$(dirname "$0")"
PYTHONPATH=py ./env/bin/python -m "$@"
# PYTHONPATH=py ./env/bin/python -m smanmi.restarter ./env/bin/python -m "$@"