#!/bin/bash

# Utility to quickly start task, like `./run nuru.recorder`

cd "$(dirname "$0")"
PYTHONPATH=py ./env/bin/python -m "$@"
#PYTHONPATH=py ./env/bin/python -m smanmi.restarter ./env/bin/python -m "$@"