CMAKE_MINIMUM_REQUIRED(VERSION 3.8)
SET(CMAKE_CXX_STANDARD 11)
SET(CMAKE_CXX_STANDARD_REQUIRED True)

PROJECT(nuru)

FIND_PACKAGE(OpenCV REQUIRED)
INCLUDE_DIRECTORIES(${OpenCV_INCLUDE_DIRS})
LIST(APPEND EXTRA_LIBS ${OpenCV_LIBS})

FIND_PACKAGE(freenect2 REQUIRED)
INCLUDE_DIRECTORIES(${freenect2_INCLUDE_DIRS})
LIST(APPEND EXTRA_LIBS ${freenect2_LIBRARIES})

ADD_EXECUTABLE(kinect features.cc hardware.cc kinect.cc network.cc util.cc viewer.cc)
TARGET_LINK_LIBRARIES(kinect PUBLIC ${EXTRA_LIBS})

ADD_EXECUTABLE(test_ test.cc)
TARGET_LINK_LIBRARIES(test_ PUBLIC ${EXTRA_LIBS})
