# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rizhom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/rizhom.proto',
  package='rizhom',
  syntax='proto3',
  serialized_pb=_b('\n\x12proto/rizhom.proto\x12\x06rizhom\"%\n\x06Signal\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"*\n\x07Monitor\x12\x1f\n\x07signals\x18\x01 \x03(\x0b\x32\x0e.rizhom.Signalb\x06proto3')
)




_SIGNAL = _descriptor.Descriptor(
  name='Signal',
  full_name='rizhom.Signal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rizhom.Signal.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rizhom.Signal.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=67,
)


_MONITOR = _descriptor.Descriptor(
  name='Monitor',
  full_name='rizhom.Monitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signals', full_name='rizhom.Monitor.signals', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=111,
)

_MONITOR.fields_by_name['signals'].message_type = _SIGNAL
DESCRIPTOR.message_types_by_name['Signal'] = _SIGNAL
DESCRIPTOR.message_types_by_name['Monitor'] = _MONITOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Signal = _reflection.GeneratedProtocolMessageType('Signal', (_message.Message,), dict(
  DESCRIPTOR = _SIGNAL,
  __module__ = 'proto.rizhom_pb2'
  # @@protoc_insertion_point(class_scope:rizhom.Signal)
  ))
_sym_db.RegisterMessage(Signal)

Monitor = _reflection.GeneratedProtocolMessageType('Monitor', (_message.Message,), dict(
  DESCRIPTOR = _MONITOR,
  __module__ = 'proto.rizhom_pb2'
  # @@protoc_insertion_point(class_scope:rizhom.Monitor)
  ))
_sym_db.RegisterMessage(Monitor)


# @@protoc_insertion_point(module_scope)
